### ISSUE TITLE
win10 py3 运行时报错误

### ISSUE THREAD

**Issue by Eisx11o** [super-l/superl-url#8]
[1;33;40mplease input keyword:资讯
Search Number of pages:20
[1;37;40m[*]Search Engine [baidu] starting！The number of display bars per page is 50
[1;37;40m[*]Search Engine [sougou] starting！The number of display bars per page is 50
[1;37;40m[*]Search Engine [so] starting！The number of display bars per page is 10
[1;37;40m[*]Search Engine [sougou],Page [1] Start collecting.
Process Process-2:
Traceback (most recent call last):
  File "C:\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Python37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\eLisx\Desktop\superl-url\core\collect.py", line 58, in __init__
    self.collection()
  File "C:\Users\eLisx\Desktop\superl-url\core\collect.py", line 78, in collection
    my_sougou = Sougou(self.outfile)
  File "C:\Users\eLisx\Desktop\superl-url\module\sougou\sougou.py", line 37, in __init__
    Engine.__init__(self, search_name, outfile)
  File "C:\Users\eLisx\Desktop\superl-url\module\engine.py", line 37, in __init__
    self.filter = Filter()
  File "C:\Users\eLisx\Desktop\superl-url\core\filter.py", line 43, in __init__
    self.filterTitleList = self.get_filtertitle()
  File "C:\Users\eLisx\Desktop\superl-url\core\filter.py", line 89, in get_filtertitle
    file_context = file_object.read().decode("utf-8")
UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 18: illegal multibyte sequence
[1;37;40m[*]Search Engine [baidu],Page [1] Start collecting.
Process Process-1:
Traceback (most recent call last):
  File "C:\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Python37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\eLisx\Desktop\superl-url\core\collect.py", line 58, in __init__
    self.collection()
  File "C:\Users\eLisx\Desktop\superl-url\core\collect.py", line 70, in collection
    my_baidu = Baidu(self.outfile)
  File "C:\Users\eLisx\Desktop\superl-url\module\baidu\baidu.py", line 39, in __init__
    Engine.__init__(self, search_name, outfile)
  File "C:\Users\eLisx\Desktop\superl-url\module\engine.py", line 37, in __init__
    self.filter = Filter()
  File "C:\Users\eLisx\Desktop\superl-url\core\filter.py", line 43, in __init__
    self.filterTitleList = self.get_filtertitle()
  File "C:\Users\eLisx\Desktop\superl-url\core\filter.py", line 89, in get_filtertitle
    file_context = file_object.read().decode("utf-8")
UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 18: illegal multibyte sequence
[1;37;40m[*]Search Engine [so],Page [1] Start collecting.
Process Process-3:
Traceback (most recent call last):
  File "C:\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Python37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\eLisx\Desktop\superl-url\core\collect.py", line 58, in __init__
    self.collection()
  File "C:\Users\eLisx\Desktop\superl-url\core\collect.py", line 74, in collection
    my_so = So(self.outfile)
  File "C:\Users\eLisx\Desktop\superl-url\module\so\so.py", line 37, in __init__
    Engine.__init__(self, search_name, outfile)
  File "C:\Users\eLisx\Desktop\superl-url\module\engine.py", line 37, in __init__
    self.filter = Filter()
  File "C:\Users\eLisx\Desktop\superl-url\core\filter.py", line 43, in __init__
    self.filterTitleList = self.get_filtertitle()
  File "C:\Users\eLisx\Desktop\superl-url\core\filter.py", line 89, in get_filtertitle
    file_context = file_object.read().decode("utf-8")
UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 18: illegal multibyte sequence
[1;33;40[*]The url collection task is complete! runs in 14 seconds

**Comment by 312818490** [comment]
把文件用记事本打开，然后另存为，下面编码选ANSI就好。
